spring.profiles.active=${ENV:dev}

# Global File Upload Configuration (can be overridden by profile-specific properties)
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB